version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/tools/cs-fixer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/tools/infection"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/tools/phpbench"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/tools/phpstan"
    schedule:
      interval: "monthly"
  - package-ecosystem: "composer"
    directory: "/tools/psalm"
    schedule:
      interval: "monthly"